<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class GraduadosSeeder extends Seeder
{
    public function run()
    {
        $graduados = [
            [
                'nombre' => 'Ana',
                'apellido' => 'Pérez',
                'dni' => '23456789',
                'fecha_nacimiento' => Carbon::parse('1990-08-15'),
                'ciudad_id' => 2,
                'contacto' => 'ana.perez90@example.com',
                'experiencia_anios' => 'menos_5',
                'habilidades_competencias' => 'Python, Cybersecurity, AWS',
                'cv' => 'https://drive.google.com/drive/u/0/folders/18FEyG4weYZdZOEiRE0xB14LERPmjjkO2',
                'interes_comunidad' => true,
                'interes_oferta' => true,
                'interes_demanda' => false,
                'validado' => true,
                'visibilidad_contacto' => true,
                'visibilidad_laboral' => true,
                'visibilidad_formacion' => false
            ],
            [
                'nombre' => 'Javier',
                'apellido' => 'García',
                'dni' => '34567890',
                'fecha_nacimiento' => Carbon::parse('1985-11-25'),
                'ciudad_id' => 3,
                'contacto' => 'javier.garcia85@example.com',
                'experiencia_anios' => 'de_10_a_20',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => false,
                'interes_oferta' => true,
                'interes_demanda' => true,
                'validado' => true,
                'visibilidad_contacto' => false,
                'visibilidad_laboral' => true,
                'visibilidad_formacion' => false
            ],
            [
                'nombre' => 'Carla',
                'apellido' => 'López',
                'dni' => '45678901',
                'fecha_nacimiento' => Carbon::parse('1992-04-12'),
                'ciudad_id' => 4,
                'contacto' => 'carla.lopez92@example.com',
                'experiencia_anios' => 'de_5_a_10',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => false,
                'interes_demanda' => true,
                'validado' => true,
                'visibilidad_contacto' => true,
                'visibilidad_laboral' => false,
                'visibilidad_formacion' => false
            ],
            [
                'nombre' => 'Diego',
                'apellido' => 'Fernández',
                'dni' => '56789012',
                'fecha_nacimiento' => Carbon::parse('1988-09-30'),
                'ciudad_id' => 5,
                'contacto' => 'diego.fernandez88@example.com',
                'experiencia_anios' => 'menos_5',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => false,
                'interes_oferta' => true,
                'interes_demanda' => true,
                'validado' => true,
                'visibilidad_contacto' => false,
                'visibilidad_laboral' => false,
                'visibilidad_formacion' => false
            ],
            [
                'nombre' => 'Elena',
                'apellido' => 'Martínez',
                'dni' => '67890123',
                'fecha_nacimiento' => Carbon::parse('1964-02-22'),
                'ciudad_id' => 6,
                'contacto' => 'elena.martinez94@example.com',
                'experiencia_anios' => 'mas_20',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => false,
                'interes_demanda' => true,
                'validado' => true,
                'visibilidad_contacto' => true,
                'visibilidad_laboral' => false,
                'visibilidad_formacion' => true
            ],
            [
                'nombre' => 'Federico',
                'apellido' => 'Torres',
                'dni' => '78901234',
                'fecha_nacimiento' => Carbon::parse('1987-12-14'),
                'ciudad_id' => 2,
                'contacto' => 'federico.torres87@example.com',
                'experiencia_anios' => 'de_5_a_10',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => false,
                'interes_oferta' => true,
                'interes_demanda' => true,
                'validado' => true,
                'visibilidad_contacto' => true,
                'visibilidad_laboral' => true,
                'visibilidad_formacion' => true
            ],
            [
                'nombre' => 'Gabriela',
                'apellido' => 'Sánchez',
                'dni' => '89012345',
                'fecha_nacimiento' => Carbon::parse('1991-03-05'),
                'ciudad_id' => 3,
                'contacto' => 'gabriela.sanchez91@example.com',
                'experiencia_anios' => 'de_5_a_10',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => false,
                'interes_demanda' => true,
                'validado' => true,
                'visibilidad_contacto' => false,
                'visibilidad_laboral' => true,
                'visibilidad_formacion' => true
            ],
            [
                'nombre' => 'Héctor',
                'apellido' => 'Ruiz',
                'dni' => '90123456',
                'fecha_nacimiento' => Carbon::parse('1989-07-28'),
                'ciudad_id' => 4,
                'contacto' => 'hector.ruiz89@example.com',
                'experiencia_anios' => 'de_5_a_10',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => false,
                'interes_oferta' => true,
                'interes_demanda' => true,
                'validado' => true,
                'visibilidad_contacto' => false,
                'visibilidad_laboral' => false,
                'visibilidad_formacion' => true
            ],
            [
                'nombre' => 'Inés',
                'apellido' => 'Fernández',
                'dni' => '01234567',
                'fecha_nacimiento' => Carbon::parse('1995-01-17'),
                'ciudad_id' => 5,
                'contacto' => 'ines.fernandez95@example.com',
                'experiencia_anios' => 'menos_5',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => false,
                'interes_demanda' => true,
                'validado' => true,
                'visibilidad_contacto' => true,
                'visibilidad_laboral' => true,
                'visibilidad_formacion' => false
            ],
            [
                'nombre' => 'Juan',
                'apellido' => 'Rodríguez',
                'dni' => '11223344',
                'fecha_nacimiento' => Carbon::parse('1986-06-01'),
                'ciudad_id' => 2,
                'contacto' => 'juan.rodriguez86@example.com',
                'experiencia_anios' => 'de_10_a_20',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => false,
                'interes_oferta' => true,
                'interes_demanda' => true,
                'validado' => true,
                'visibilidad_contacto' => true,
                'visibilidad_laboral' => false,
                'visibilidad_formacion' => true
            ],
            [
                'nombre' => 'Gonzalo',
                'apellido' => 'Riquelme Ludwig',
                'dni' => '43099502',
                'fecha_nacimiento' => Carbon::parse('2000-11-08'),
                'ciudad_id' => 2,
                'contacto' => 'gonzariquelme66@gmail.com',
                'experiencia_anios' => 'menos_5',
                'habilidades_competencias' => 'Desarrollo soluciones para clientes en .NET, Angular y SQLServer',
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => false,
                'interes_demanda' => true,
                'validado' => false,
                'visibilidad_contacto' => true,
                'visibilidad_laboral' => true,
                'visibilidad_formacion' => false
            ],
            [
                'nombre' => 'Dylan',
                'apellido' => 'Hughes',
                'dni' => '43091302',
                'fecha_nacimiento' => Carbon::parse('2000-10-13'),
                'ciudad_id' => 2,
                'contacto' => 'dylanhughes028@gmail.com',
                'experiencia_anios' => 'menos_5',
                'habilidades_competencias' => 'Resolucion de diversas problemáticas para la empresa',
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => true,
                'interes_demanda' => false,
                'validado' => false,
                'visibilidad_contacto' => true,
                'visibilidad_laboral' => true,
                'visibilidad_formacion' => true
            ]
        ];

        DB::table('graduados')->insert($graduados);
    }
}
