<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class GraduadosSeeder extends Seeder
{
    public function run()
    {
        $graduados = [
            [
                'nombre' => 'Ana Pérez',
                'dni' => '23456789',
                'fecha_nacimiento' => Carbon::parse('1990-08-15'),
                'ciudad_id' => 2,
                'contacto' => 'ana.perez90@example.com',
                'ocupacion_trabajo' => 'autonomo',
                'ocupacion_empresa' => null,
                'ocupacion_sector' => 'privado',
                'ocupacion_informacion_adicional' => 'Consultora de TI especializada en ciberseguridad.',
                'experiencia_anios' => 'menos_5',
                'habilidades_competencias' => '"Python, Cybersecurity, AWS"',
                'cv' => 'https://drive.google.com/drive/u/0/folders/18FEyG4weYZdZOEiRE0xB14LERPmjjkO2',
                'interes_comunidad' => true,
                'interes_oferta' => true,
                'interes_demanda' => false,
                'validado' => true
            ],
            [
                'nombre' => 'Javier García',
                'dni' => '34567890',
                'fecha_nacimiento' => Carbon::parse('1985-11-25'),
                'ciudad_id' => 3,
                'contacto' => 'javier.garcia85@example.com',
                'ocupacion_trabajo' => 'rel_dependencia',
                'ocupacion_empresa' => 'Dow',
                'ocupacion_sector' => 'privado',
                'ocupacion_informacion_adicional' => 'Bioquímico en la planta de DOW.',
                'experiencia_anios' => 'de_10_a_20',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => false,
                'interes_oferta' => true,
                'interes_demanda' => true,
                'validado' => true
            ],
            [
                'nombre' => 'Carla López',
                'dni' => '45678901',
                'fecha_nacimiento' => Carbon::parse('1992-04-12'),
                'ciudad_id' => 4,
                'contacto' => 'carla.lopez92@example.com',
                'ocupacion_trabajo' => 'rel_dependencia',
                'ocupacion_empresa' => 'Farmacity',
                'ocupacion_sector' => 'privado',
                'ocupacion_informacion_adicional' => null,
                'experiencia_anios' => 'de_5_a_10',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => false,
                'interes_demanda' => true,
                'validado' => true
            ],
            [
                'nombre' => 'Diego Fernández',
                'dni' => '56789012',
                'fecha_nacimiento' => Carbon::parse('1988-09-30'),
                'ciudad_id' => 5,
                'contacto' => 'diego.fernandez88@example.com',
                'ocupacion_trabajo' => 'autonomo',
                'ocupacion_empresa' => null,
                'ocupacion_sector' => 'privado',
                'ocupacion_informacion_adicional' => 'Contabilidad para Monotributistas y pymes.',
                'experiencia_anios' => 'menos_5',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => false,
                'interes_oferta' => true,
                'interes_demanda' => true,
                'validado' => true
            ],
            [
                'nombre' => 'Elena Martínez',
                'dni' => '67890123',
                'fecha_nacimiento' => Carbon::parse('1964-02-22'),
                'ciudad_id' => 6,
                'contacto' => 'elena.martinez94@example.com',
                'ocupacion_trabajo' => 'rel_dependencia',
                'ocupacion_empresa' => 'Ministerio de Obras Públicas',
                'ocupacion_sector' => 'publico',
                'ocupacion_informacion_adicional' => null,
                'experiencia_anios' => 'mas_20',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => false,
                'interes_demanda' => true,
                'validado' => true
            ],
            [
                'nombre' => 'Federico Torres',
                'dni' => '78901234',
                'fecha_nacimiento' => Carbon::parse('1987-12-14'),
                'ciudad_id' => 2,
                'contacto' => 'federico.torres87@example.com',
                'ocupacion_trabajo' => 'rel_dependencia',
                'ocupacion_empresa' => 'Escuela Don Bosco',
                'ocupacion_sector' => 'privado',
                'ocupacion_informacion_adicional' => null,
                'experiencia_anios' => 'de_5_a_10',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => false,
                'interes_oferta' => true,
                'interes_demanda' => true,
                'validado' => true
            ],
            [
                'nombre' => 'Gabriela Sánchez',
                'dni' => '89012345',
                'fecha_nacimiento' => Carbon::parse('1991-03-05'),
                'ciudad_id' => 3,
                'contacto' => 'gabriela.sanchez91@example.com',
                'ocupacion_trabajo' => 'rel_dependencia',
                'ocupacion_empresa' => 'Hospital Municipal',
                'ocupacion_sector' => 'publico',
                'ocupacion_informacion_adicional' => 'Medico Clínico',
                'experiencia_anios' => 'de_5_a_10',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => false,
                'interes_demanda' => true,
                'validado' => true
            ],
            [
                'nombre' => 'Héctor Ruiz',
                'dni' => '90123456',
                'fecha_nacimiento' => Carbon::parse('1989-07-28'),
                'ciudad_id' => 4,
                'contacto' => 'hector.ruiz89@example.com',
                'ocupacion_trabajo' => 'rel_dependencia',
                'ocupacion_empresa' => 'Spotify',
                'ocupacion_sector' => 'privado',
                'ocupacion_informacion_adicional' => null,
                'experiencia_anios' => 'de_5_a_10',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => false,
                'interes_oferta' => true,
                'interes_demanda' => true,
                'validado' => true
            ],
            [
                'nombre' => 'Inés Fernández',
                'dni' => '01234567',
                'fecha_nacimiento' => Carbon::parse('1995-01-17'),
                'ciudad_id' => 5,
                'contacto' => 'ines.fernandez95@example.com',
                'ocupacion_trabajo' => 'autonomo',
                'ocupacion_empresa' => null,
                'ocupacion_sector' => 'privado',
                'ocupacion_informacion_adicional' => 'Gestiono un emprendimiento personal',
                'experiencia_anios' => 'menos_5',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => false,
                'interes_demanda' => true,
                'validado' => true
            ],
            [
                'nombre' => 'Juan Rodríguez',
                'dni' => '11223344',
                'fecha_nacimiento' => Carbon::parse('1986-06-01'),
                'ciudad_id' => 2,
                'contacto' => 'juan.rodriguez86@example.com',
                'ocupacion_trabajo' => 'rel_dependencia',
                'ocupacion_empresa' => 'Escuela Don Bosco',
                'ocupacion_sector' => 'privado',
                'ocupacion_informacion_adicional' => 'Profesor de Física de 4to año',
                'experiencia_anios' => 'de_10_a_20',
                'habilidades_competencias' => null,
                'cv' => null,
                'interes_comunidad' => false,
                'interes_oferta' => true,
                'interes_demanda' => true,
                'validado' => true
            ],
            [
                'nombre' => 'Gonzalo Riquelme Ludwig',
                'dni' => '43099502',
                'fecha_nacimiento' => Carbon::parse('2000-11-08'),
                'ciudad_id' => 2,
                'contacto' => 'gonzalo.riquelme@uns.com',
                'ocupacion_trabajo' => 'rel_dependencia',
                'ocupacion_empresa' => 'Assertia',
                'ocupacion_sector' => 'privado',
                'ocupacion_informacion_adicional' => 'Desarrollador full-stack',
                'experiencia_anios' => 'menos_5',
                'habilidades_competencias' => 'Desarrollo soluciones para clientes en .NET, Angular y SQLServer',
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => false,
                'interes_demanda' => true,
                'validado' => false
            ],
            [
                'nombre' => 'Dylan Hughes',
                'dni' => '43091302',
                'fecha_nacimiento' => Carbon::parse('2000-10-14'),
                'ciudad_id' => 2,
                'contacto' => 'dylan.basket@uns.com',
                'ocupacion_trabajo' => 'rel_dependencia',
                'ocupacion_empresa' => 'Codimat',
                'ocupacion_sector' => 'privado',
                'ocupacion_informacion_adicional' => 'Pasante en el area de IT.',
                'experiencia_anios' => 'menos_5',
                'habilidades_competencias' => 'Resolucion de diversas problemáticas para la empresa',
                'cv' => null,
                'interes_comunidad' => true,
                'interes_oferta' => true,
                'interes_demanda' => false,
                'validado' => false
            ]
        ];

        DB::table('graduados')->insert($graduados);
    }
}
