[phases.setup]
nixPkgs = ["php81", "composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "mkdir -p storage/framework/cache",
  "mkdir -p storage/framework/sessions",
  "mkdir -p storage/framework/views",
  "chmod -R 777 storage/framework bootstrap/cache"
]
